### ISSUE TITLE
name parameter is not working for get activation summary api

### ISSUE THREAD

**Issue by ShubhamGupta9582** [apache/openwhisk#4903] opened 2020-05-13 10:33 UTC
Hi guys,

I'm looking for the api which gives activation list of particular action and I found that api but the **name query param** is not woking in **get activation summary** api. when i put name of the action in this param it gives empty list.

Below is the swagger link where i found that activation api
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openwhisk/openwhisk/master/core/controller/src/main/resources/apiv1swagger.json#/Activations/getActivations

**Comment by rabbah** [comment] 2020-05-13 13:03
`?name=action-name` or `?name=package-name/action-name` would filter activations for those actions. If your action is in a package, provide the package name to qualify the action name.

If you have the `wsk` CLI you can use `wsk -v` to see the URL called.

**Comment by ShubhamGupta9582** [comment] 2020-05-13 17:35
yes, I have tried both (**?name=action-name or ?name=package-name/action-name**) ways. but it didn't work.

**Comment by rabbah** [comment] 2020-05-13 18:19
omit `guest/` - this is the namespace.

so it should be `?name=CalculateU_M`

**Comment by ShubhamGupta9582** [comment] 2020-05-14 06:59
I had tried this way also but it did not return the expected output. you can see in attached screenshots
![Screenshot from 2020-05-14 12-25-05](https://user-images.githubusercontent.com/30547263/81902895-841d1c00-95de-11ea-9aea-1fbed0dcc9a2.png)
![Screenshot from 2020-05-14 12-25-21](https://user-images.githubusercontent.com/30547263/81902900-854e4900-95de-11ea-86e5-4ad56b0bcb2f.png)

**Comment by jiangpengcheng** [comment] 2020-06-11 09:13
I met this problems too, is `CalculateU_M` imported from a shared package?

**Comment by ShubhamGupta9582** [comment] 2020-06-11 12:08
I did not explicitly provide any package when created this action. So, it would be in default package.

**Comment by rabbah** [comment] 2020-08-06 20:40
@jiangpengcheng from the screenshots the action was not in an action.
I can't reproduce this. Going to close this - reopen if there are more details to make this actionable (how was action created, how is openwhisk deployed).

**Closed by rabbah** 2020-08-06 20:40 UTC
