### ISSUE TITLE
web action should not return 200 status on action error

### ISSUE THREAD

**Issue by mdeuser** [apache/openwhisk#2237] opened 2017-05-12 20:11 UTC
## Environment details:

* local deployment, vagrant

## Steps to reproduce the issue:

1.   Create an action called testrej with `function main(m) { return Promise.reject({error:'bad news!'}); }`
2.   Invoke as regular action: `wsk action invoke testrej -b -v`
3.   Invoke as web action: `curl -v http://YOURHOST/api/v1/experimental/web/guest/default/testrej.json`
4.  Observe the HTTP response code in (2) and (3)

## Provide the expected results and outputs:

Both response codes are 502

## Provide the actual results and outputs:

Response code for (2) is 502.  Response code for (3) is 200

## Additional information you deem important:
* Possibly a related issue.. actions invoked as standard actions have their `return Promise.reject(string)` results automatically encapsulated into the appropriate activation JSON structure for consumption by the caller. However, when the same action is invoked as a .json web action, the response code is 400 (not valid application/json) - having a similar automatic encapsulation for strings (and even objects) would be helpful (i.e. `{ error: RESPONSE}`) with 502 status code.

**Comment by rabbah** [comment] 2017-06-22 02:56
This is working as designed.

**Comment by rabbah** [comment] 2017-11-29 20:11
The issue here is that the `json` extension defines only a default status code (200 `OK`). If control over the status code is desired, `.http` or no extension is used. Would we change the status code to `40x` for all extensions or some extensions if the response contains an error? @joelmarty do you have a suggestion?

**Comment by joelmarty** [comment] 2017-11-30 08:11
I can report my experience rather than make a suggestion:
I have a function, very simple, that returns a Promise object on execution.
The promise is either rejected with the error object as argument or resolved with a simple json object.

I can observe the following:
- using the webaction, I get a 204 no content status and no body (obviously) when calling my web action, whether it results in an error or not (I can see in the functions monitor there's an error).
- using the api gateway, I get a 200 response whether the action succeeds or not. The response object is ok on success and empty or failure (I think this is more a problem with the code)

Obviously we're talking about web actions here but the behavior I observe in any case is quite discouraging to pursue any endeavor to build apis using openwhisk.

If there is any way that we can control the http status code of the response, please tell me because I could find no documentation on the topic. Maybe that's the real issue here.

**Comment by rabbah** [comment] 2017-11-30 12:06
https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md You’ll want to return a JSON object containing these three properties: `{statusCode, body, headers}`. The values have default defined if omitted but you can most certainly use a web action to build an API.

**Comment by joelmarty** [comment] 2017-12-01 09:14
That's actually very helpful, I completely missed that documentation page. I will make some tests and give any remarks.

**Closed** 2019-12-18 15:24 UTC
Labels: API, question
