### ISSUE TITLE
[Feature request] Hide codes or parameters from shared package

### ISSUE THREAD

**Issue by style95** [apache/openwhisk#3015] opened 2017-11-28 03:57 UTC
Since it is common that someone want to share his features but does not want to reveal its internal or any secrets, it would be great if we can hide codes or default parameters from actions in shared package.

**Comment by rabbah** [comment] 2017-11-28 09:04
A general thought here is to have more fine grained entitlement - read, write, execute for example where today execute is tied to read. Note though that if you’re just making execute possible your action is just an api at this point. What’s the advantage of making the action part of package that is public but execute only? Perhaps composition. I’m not sure I see another benefit. What are your thoughts?

(This has come up before; will cross link.)

**Comment by rabbah** [comment] 2017-11-28 09:07
A further issue one would need to consider here is who owns the activation record for such an action. If the caller owns it then they have access to the logs which could leak information. So I’m past discussions around this topic, we’ve debated two facets to the activation: one for the owner and another for the caller.

**Comment by style95** [comment] 2017-11-28 09:33
For example, I want to share features to send email or SMS.
My action will call API from email or sms provider.

I want to make anyone to send email with his `sender`, `recipients`, `contents` and so on.
But for this, email provider may ask some secrets to grant it.
I can hardcode or pass secrets as default parameters.
But in both the cases, secrets will be exposed when user bind my shared package.

User will bind my package and invoke it in his namespace.
So activation will be stored in his namespace.
If I can hide code or default parameters, it will not be exposed in activation records.

**Comment by rabbah** [comment] 2017-11-28 09:47
You’d need to be careful not to log anything that would leak details (eg better not log parameters) so in general the entitlement has to extend to the activation record to restrict log access.

Another indirect point related to the activation record is that the caller “pays”. Another option would be using an authenticated web action with the activation owned by the caller.

**Comment by style95** [comment] 2017-11-28 09:50
If user bind the package and invoke a bound action, would activation be stored in original namespace?

**Comment by rabbah** [comment] 2017-11-28 10:03
I don’t understand the question. Today the caller namespace owns the activation record for any action invoked via the POST API. And the owning namespace owns the activation for a web action.

When you’re granting execute only writes it’s like a web action except in this case it is also desirable to defer the activation cost to the caller. So we could implement it this way, for example.

**Comment by style95** [comment] 2017-11-28 10:51
If "pays" means cost for activation(invoking the action), I think it is reasonable that belongs to caller. Activation for bound action will go to binding namespace. So it might be enough.

And sharing package is great and consistent way to distribute the features.
User can navigate all shared packages and just bind desired one and use it in his namespace.
(Though currently it is not possible to navigate all shared packages via OW API.)

I just want to follow this whole process. So exposing a web action may not be appropriate for this case.(I should manually let them know the url for my web action)

I just naively thought, it would be great if there are flags for `hiding codes` or `hiding parameters` when I share my package.

Regarding information exposed in log, I think it is quite similar to the one in default parameters.
Someone who shares his package should take care for that risk.
Also sometime, caller want to see what happens. Specifically, if he can't see the internals and got error response, highly likely he will want to look into the logs.

So I think it might be enough to have options for hiding codes only.
Since storing codes as attachment is in progress, we may just filter out codes from the response.

**Comment by rabbah** [comment] 2017-11-28 13:26
I propose to close this issue as a duplicate of https://github.com/apache/incubator-openwhisk/issues/2155.

The log issue is a bigger deal than hijacking parameters (for which we have a mechanism to protect values with `final`) and we should think of the implications carefully.

In general, I think what you gain from having an execute only action is convenience for composition. Otherwise, it's just an API and there are other mechanisms for API discovery that we can be applied.

That said, more fine grain entitlement is something that's been discussed before so it's worth keeping the discussion up.

**Comment by style95** [comment] 2017-11-29 05:05
I am fine to close this issue.

Could you explain more about what you mentioned or have me get any reference?

I think I am not aware of `final`, `composition` and `API discovery`.
What are those use-cases? Is it already supported by OW now?

**Comment by rabbah** [comment] 2020-08-27 15:40
this was implemented by https://github.com/apache/openwhisk/pull/4935.

**Closed by rabbah** 2020-08-27 15:40 UTC
Labels: enhancement
