### ISSUE TITLE
How to upgrade invoker gracefully

### ISSUE THREAD

**Issue by ningyougang** [apache/openwhisk#2678] opened 2017-08-31 07:19 UTC
If i want to upgrade the `invoker` component using new image.
When use `-e mode=clean` to remove invoker, the relative action containers will be removed.
But may be the action containers are doing the user's task.
So i am not sure whether we can use `-e mode=clean` to remove invoker.

How can i upgrade the invoker and has no bad influences on the running action containers?

As for as i know, currently, there has no solution to support `graceful shutdown for invoker`.

Can we have any plan to support it?

One idea: when execute `-e mode=clean`, the invoker should judge whether it completed all its child actions. If completed, then `do the remove invoker action` really.

**Comment by markusthoemmes** [comment] 2017-08-31 08:57
The invoker does already have a shutdown hook which is supposed to clean up. That hook needs to wait until all the user load is finished and then return so the container can be removed. It also needs to make sure no load is accepted anymore (potentially by stop sending pings to the controller).

If we're able to do that, we can remove the ansible jobs which clean up and gain the functionality that you're after.

**Comment by rabbah** [comment] 2019-12-18 15:26
closing as duplicate of 3681.

**Closed by rabbah** 2019-12-18 15:26 UTC
Labels: deployment, invoker
