### ISSUE TITLE
actions can get wedged, showing up in list views, but 404 on get and delete

### ISSUE THREAD

**Issue by starpit** [apache/openwhisk#4001] opened 2018-09-04 12:18 UTC
The bug is that actions can get "wedged" into a namespace, where they continue to show up in the list views, but the controller yields 404s on action GET and DELETE. more oddly, action update gives back a "concurrent modification to resource detected" message! (no concurrency involved, from my end)

## Environment details:

* i've only tried us-south IBM Cloud Functions

## Steps to reproduce the issue:

i'm not quite sure yet, but so far, i've only been able to trigger this bug when creating Conductor actions. i'll continue to try to figure this one out

we had a wedged namespace a few weeks ago (from our initial correspondence on this topic), and it seems to have unwedged itself (after a week or so); perhaps because the controller was rebooted?

## Provide the expected results and outputs:

after wiping all assets, the list view should be a empty

## Provide the actual results and outputs:
![screen shot 2018-09-01 at 20 29 11](https://user-images.githubusercontent.com/4741620/45030679-a8a7af00-b01a-11e8-9063-4e76fa643949.png)
![screen shot 2018-09-01 at 20 31 34](https://user-images.githubusercontent.com/4741620/45030681-aba29f80-b01a-11e8-9e54-a01b94eca374.png)
![screen shot 2018-09-01 at 20 40 29](https://user-images.githubusercontent.com/4741620/45030682-ad6c6300-b01a-11e8-85f5-6ea800b6d532.png)

**Comment by rasantiago** [comment] 2019-05-13 14:49
@starpit Did you ever get a resolution to this issue.  I am experiencing the same issue.

**Comment by starpit** [comment] 2019-05-17 16:16
not on my end. this was (still is? not sure) a backend issue with view consistency in openwhisk. unfortunately, i don't know (one way or the other) if any progress has been made on it.

**Comment by rabbah** [comment] 2019-12-18 14:09
This is a duplicate of #2051.

**Closed by rabbah** 2019-12-18 14:09 UTC

**Comment by ShubhamGupta9582** [comment] 2020-04-01 14:28
I'm also getting this error. action is showing in action list but when deleting it **404** error comes. and when updating this action **Concurrent modification to resource detected** error comes.

**Comment by bdoyle0182** [comment] 2022-12-08 22:28
this occurs when an action is missing the attachment stored in the attached db. in the fix commit, the action will still correctly return a 404 if you try to perform a GET; but you will now be able to delete or overwrite the function to mitigate and redeploy
