### ISSUE TITLE
invoker should not reuse warm container of a deleted action

### ISSUE THREAD

**Issue by tysonnorris** [apache/openwhisk#3151] opened 2018-01-06 01:03 UTC
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
* version of docker, vagrant, ubuntu, ...

## Steps to reproduce the issue:

1.   create action test
2.   invoke action test (results in a warm container)
3.   delete action test
4.   create action test (note: make sure the action has the same name)
5.   invoke action test (note that warm container for the deleted action is used)

## Provide the expected results and outputs:

Should use a free/new container (and not the warm container)

## Provide the actual results and outputs:

Invoker will use the warm container (see invoker logs indicating resume/unpause)

## Additional information you deem important:

This issue may be avoided by using the document revision id, in addition to the entity name + version. (I haven't tested this yet)

**Comment by rabbah** [comment] 2018-01-06 01:07
This is I think a duplicate of https://github.com/apache/incubator-openwhisk/issues/3120

**Comment by tysonnorris** [comment] 2018-01-06 01:15
agreed looks like a duplicate, however at least one of our environments we are getting monitoring failures of "connection reset" when this occurs, but that may be unrelated; And this behavior was unexpected (didn't realize that code changes would be required to cause a re-init). Will verify that this does not occur when there are code changes, and close based on that. (and will separately look at the other issue which may be more related to using paused containers)

**Comment by tysonnorris** [comment] 2018-01-08 18:33
@rabbah I confirmed that the container is not reused when code is changed; 

However what I see in the logs of our env is that the container is reused between 3 and 20 times, but always eventually generates a `ConnectionError(java.net.SocketException: Connection reset)` error, causing an error. 

This happens with a monitor that creates an action, executes it, and then deletes it, which operates every 5 minutes. I expect the container to be reused "indefinitely",. since the 10 minute "unused" limit is not reached, and there is not additional traffic in the system (to cause the container to get destroyed so other actions can run). 

It does not happen if the action is created each time with a unique name.

**Comment by markusthoemmes** [comment] 2018-01-08 19:34
@tysonnorris any possibility that the action itself has a bug? This happens if the action proxy crashes due to a memory leak for example.

**Comment by rabbah** [comment] 2018-01-08 19:37
+1 is there a resource leak that causes the container to crash?
you can just run the same action 20+ times without deleting it with 100ms think time and see if it also crashes then.

**Comment by tysonnorris** [comment] 2018-01-08 23:56
The code is pretty simple: `function main(){return {};}`
I haven't been able to script it to crash; I'll investigate update here (or create a new issue) if I get it to the point of reproducing on demand.

Here's an invoker log of one of the failures; you can see the pause previous to the failure
```
[2018-01-05T18:33:44.163Z] [INFO] [#tid_145829] [DockerContainer] sending arguments to /guest/runscope at ContainerId(fad17fd8ab3aab47c7bed3ff94185534e33028b8e2d6754164597d0aea709f19) ContainerAddress(172.17.0.4,8080) [marker:invoker_activationRun_start:317]
[2018-01-05T18:33:44.166Z] [INFO] [#tid_145829] [DockerContainer] running result: ok [marker:invoker_activationRun_finish:320:2]
[2018-01-05T18:33:44.167Z] [INFO] [#tid_145829] [ContainerProxy]  [marker:invoker_collectLogs_start:321]
[2018-01-05T18:33:44.169Z] [INFO] [#tid_145829] [ContainerProxy]  [marker:invoker_collectLogs_finish:323:2]
[2018-01-05T18:33:44.169Z] [INFO] [#tid_145829] [InvokerReactive] recording the activation result to the data store
[2018-01-05T18:33:44.170Z] [INFO] [#tid_145829] [CouchDbRestStore] [PUT] 'whisk_dev_activations' saving document: 'id: guest/3bc9f8f49288445489f8f49288d454e5, rev: null' [marker:database_saveDocument_start:324]
[2018-01-05T18:33:44.170Z] [INFO] [??] [CouchDbRestStore] 'whisk_dev_activations' saving 1 documents [marker:database_saveDocumentBulk_start:4954249]
[2018-01-05T18:33:44.170Z] [INFO] [#tid_145829] [InvokerReactive] posted completion of activation 3bc9f8f49288445489f8f49288d454e5
[2018-01-05T18:33:44.211Z] [INFO] [??] [CouchDbRestStore] 'whisk_dev_activations' completed 1 documents [marker:database_saveDocumentBulk_finish:4954290:41]
[2018-01-05T18:33:44.211Z] [INFO] [#tid_145829] [CouchDbRestStore] [PUT] 'whisk_dev_activations' completed document: 'id: guest/3bc9f8f49288445489f8f49288d454e5, rev: null', response: 'id: guest/3bc9f8f49288445489f8f49288d454e5, rev: 1-4309f65af7d429a0180e0900f2819484' [marker:database_saveDocument_finish:365:41]
[2018-01-05T18:33:44.212Z] [INFO] [#tid_145829] [InvokerReactive] recorded activation
[2018-01-05T18:33:44.233Z] [INFO] [#sid_102] [DockerClientWithFileAccess] running /usr/bin/docker pause fad17fd8ab3aab47c7bed3ff94185534e33028b8e2d6754164597d0aea709f19 [marker:invoker_docker.pause_start:4954311]
[2018-01-05T18:33:44.255Z] [INFO] [#sid_102] [DockerClientWithFileAccess]  [marker:invoker_docker.pause_finish:4954333:22]
[2018-01-05T18:39:09.096Z] [INFO] [#sid_110] [MessageFeed] processing invoker0[0][5488] (1/16)
[2018-01-05T18:39:09.097Z] [INFO] [#tid_145858] [InvokerReactive]  [marker:invoker_activation_start:63]
[2018-01-05T18:39:09.097Z] [INFO] [#tid_145858] [InvokerReactive] guest/runscope guest a41299b5a70140369299b5a701703614
[2018-01-05T18:39:09.158Z] [INFO] [#tid_145858] [WhiskAction] [GET] serving from datastore: CacheKey(guest/runscope) [marker:database_cacheMiss_count:64]
[2018-01-05T18:39:09.158Z] [INFO] [#tid_145858] [CouchDbRestStore] [GET] 'whisk_dev_whisks' finding document: 'id: guest/runscope, rev: 13167-bbc547b503cc59e3df35bc3351a91f17' [marker:database_getDocument_start:64]
[2018-01-05T18:39:09.431Z] [INFO] [#tid_145858] [CouchDbRestStore] [GET] 'whisk_dev_whisks' completed: found document 'id: guest/runscope, rev: 13167-bbc547b503cc59e3df35bc3351a91f17' [marker:database_getDocument_finish:396:332]
[2018-01-05T18:39:09.431Z] [INFO] [#tid_145858] [DockerClientWithFileAccess] running /usr/bin/docker unpause fad17fd8ab3aab47c7bed3ff94185534e33028b8e2d6754164597d0aea709f19 [marker:invoker_docker.unpause_start:397]
[2018-01-05T18:39:09.454Z] [INFO] [#tid_145858] [DockerClientWithFileAccess]  [marker:invoker_docker.unpause_finish:420:23]
[2018-01-05T18:39:09.454Z] [INFO] [#tid_145858] [DockerContainer] sending arguments to /guest/runscope at ContainerId(fad17fd8ab3aab47c7bed3ff94185534e33028b8e2d6754164597d0aea709f19) ContainerAddress(172.17.0.4,8080) [marker:invoker_activationRun_start:420]
[2018-01-05T18:39:21.654Z] [INFO] [#tid_145858] [DockerContainer] running result: ConnectionError(java.net.SocketException: Connection reset) [marker:invoker_activationRun_finish:12620:3]
```

**Comment by markusthoemmes** [comment] 2018-07-03 13:48
This mailthread is related to the connection issues: https://lists.apache.org/thread.html/6691d334613107d7b2ecdf0caa8ced719b314942149c10f358d98ac6@%3Cdev.openwhisk.apache.org%3E

**Closed** 2019-12-18 15:52 UTC
