### ISSUE TITLE
ansible/openwhisk.yml fails with an error

### ISSUE THREAD

**Issue by tchandrahas** [apache/openwhisk#5107] opened 2021-04-25 01:14 UTC
## Environment details:

* Local Deployment 
* Ubuntu 18.04
* Python 3.6
* Ansible 2.10.8, installed using pip3 install ansible --user

## Steps to reproduce the issue:

1.  ./gradlew distDocker 
2.    ansible-playbook -i environments/$ENVIRONMENT setup.yml;  ansible-playbook -i environments/$ENVIRONMENT wipe.yml 
3.   ansible-playbook -i environments/$ENVIRONMENT openwhisk.yml

## Provide the actual results and outputs:
TASK [cli : Download release archive to build directory ...] **************************************************************************************************************************
Saturday 24 April 2021  20:02:32 -0500 (0:00:00.168)       0:01:21.005 ******** 
fatal: [172.17.0.1]: FAILED! => {"changed": false, "msg": "argument headers is of type <class 'str'> and we were unable to convert to dict: dictionary requested, could not parse JSON or key=value"}

argument headers is of type <class 'str'> and we were unable to convert to
dict: dictionary requested, could not parse JSON or key=value

PLAY RECAP ****************************************************************************************************************************************************************************
172.17.0.1                 : ok=11   changed=2    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0   
controller0                : ok=26   changed=3    unreachable=0    failed=0    skipped=14   rescued=0    ignored=0   
invoker0                   : ok=29   changed=7    unreachable=0    failed=0    skipped=25   rescued=0    ignored=0   
kafka0                     : ok=10   changed=4    unreachable=0    failed=0    skipped=7    rescued=0    ignored=0   

## Additional information you deem important:
ansible-playbook openwhisk.yml terminates with error. The error says ansible couldn't parse JSON or key=value.

**Comment by jiangpengcheng** [comment] 2021-06-07 07:30
I think this error is caused by incompatible ansible version, you can downgrade to `2.5.2` to see whether it works for now
but this is not the best option, we will try to make ansible scripts compatible with latest ansible version as soon as possible

**Comment by jebruen** [comment] 2021-09-21 23:04
Hi. I have also run into this problem. Is there any resolution? I tried downgrading ansible to 2.5.2 and I still came across this error.

**Comment by JesseStutler** [comment] 2021-11-08 13:04
I have the same error in the same task.

**Comment by JesseStutler** [comment] 2021-11-08 13:07
I followed @jiangpengcheng 's way, but got a new error:
```
TASK [Gathering Facts] ******************************************************************************************************
Monday 08 November 2021  13:06:10 +0000 (0:00:00.065)       0:00:00.065 *******
fatal: [10.2.0.65]: FAILED! => {"msg": "fragment_class is None"}

fragment_class is None
```

**Comment by upgle** [comment] 2022-07-01 02:41
Resolved by this PR https://github.com/apache/openwhisk/pull/5225

**Closed** 2022-07-01 02:42 UTC
