### ISSUE TITLE
Feat: Using pekko instead of akka

### ISSUE THREAD

**Issue by laglangyue** [apache/openwhisk#5479] opened 2024-04-27 15:06 UTC
Akka changed the protocol, pekko is TLP

**Comment by rabbah** [comment] 2024-05-06 04:05
This will prob be a large undertaking even though pekko is an akka fork. Are you interested in doing this?

**Comment by laglangyue** [comment] 2024-05-07 03:25
> This will prob be a large undertaking even though pekko is an akka fork. Are you interested in doing this?

I am pekko contrributer, and have a PEKKO committee friends, and my friends and I will do our best to give it a try

**Comment by pjfanning** [comment] 2024-05-26 23:06
this is a duplicate of https://github.com/apache/openwhisk/issues/5441

**Closed** 2024-05-27 01:25 UTC
