### ISSUE TITLE
What is distributed openwhisk and how is it installed?

### ISSUE THREAD

**Issue by spattewar** [apache/openwhisk#2928] opened 2017-11-06 04:38 UTC
Hello Experts.

What is a distributed openwhisk installation? Is it distributing the openwhisk components (invokker, kafka, controller etc) to multiple machines or it is installing openwhisk locally on each machine and then managing them using a load balancer? 
Also is there a good read me other than the one under openwhisk for distributed installation? for some reason i am not able to follow the first steps as it asks to modify the host file but doesn't mention how to do it.
really appreciate your time and help.

believe me there is no better help than asking the experts here.

regards

**Comment by spattewar** [comment] 2017-11-07 21:09
@rabbah , @markusthoemmes 
any help would be greatly appreciate. We have 6 machine and we want to build an openwhisk cluster with load balancer.
thank you for your time.
Regards

**Comment by markusthoemmes** [comment] 2017-11-08 07:27
OpenWhisk is being deployed distributed by default. Distributed means, that the components are distributed to multiple machines (it does not mean sharding/federation).

Locally, we deploy everything to one machine, but that is a deploytime detail. For our deployment we use [ansible](https://www.ansible.com/how-ansible-works). A deployment is defined by a group_vars file and a hosts file. One example for such a definition is the **local** environment, found here: https://github.com/apache/incubator-openwhisk/tree/master/ansible/environments/local

If you look through one of the hosts files, you'll see that there is a list of machines defined for every component individually. Fill in multiple IPs for the invokers and you'll get multiple invokers, one on each of the machines you entered (`ansible_host` is the address of the machine). In the local case that's `172.17.0.1` (docker's interface) but can really be any remote IP as well. Remoteness is "hidden" by ansible.

Let me know if you need further details!

**Comment by spattewar** [comment] 2017-11-08 18:50
@markusthoemmes 
thank you for your comment.

Oh ok. understand that the deployment is always distributed but for just a local deployment all the IPs of the individual components are the local docker interface.

I have 6 machines and want to create a cluster of openwhisk on them which is then controlled by a load balancer. If I follow the distributed install readme file then I would modify the hosts file and put the actual IP address of the machines instead of the local interface. But then how will the load balancing occur. Is it inbuilt in the openwhisk architecture? Also can I have many invoker for e.g. multiple on single IP?

your response is greatly appreciated.
thanks and regards

**Comment by markusthoemmes** [comment] 2017-11-09 09:14
@spattewar Multiple invokers on one machine is possible, but discouraged as one Invoker thinks its alone on the machine.

Loadbalancing between multiple invokers is built into the OpenWhisk system.

**Comment by spattewar** [comment] 2017-11-14 17:09
@markusthoemmes 
Thank you for your comments.
We want to process around 1 million events and were looking for openwhisk. So if we have to do it then how many invokers would be require and I think that would be the number of machines that I would require. unless on each machine I create multiple VMs and the IP address of these VMs are communicated in the hosts file. Of course all the VMs should have connectivity. 

your thoughts please.
Thanks and regards

**Comment by rabbah** [comment] 2017-11-14 17:35
@spattewar is this a duplicate of https://github.com/apache/incubator-openwhisk/issues/2569?

**Comment by spattewar** [comment] 2017-11-14 18:01
@rabbah 

the million event processing is but not the distributed installation configuration. After understanding the distributed installation i would really like to know how many I need to setup to process those many events. 
I think I have to install multiple VMs on a machine and do this. There is a possibility of latency as well with this I guess. 
One more thing that is not clear is the limit of the namespaces, concurrent invocations etc which will tell whether million events processing is possible or not. also is this limitation of the entire openwhisk installation or the invoker component.

sorry for the inconvenience and your time and support is greatly appreciated.

Thanks and Regards

**Comment by rabbah** [comment] 2017-11-14 18:42
great questions, keep them coming we're happy to help.

you control the limits per deployment - there are three limits to be aware of: https://github.com/apache/incubator-openwhisk/blob/master/ansible/group_vars/all#L97-L102
1. actions per minute per namespace
1. concurrent actions live at any given time per namespace
1. total concurrent actions in the system

so if you are tuning for 1M/s for the entire system vs a specific namespace, you'll need to adjust the limits accordingly.

the other knob you want to control is how many container to run per invoker vm:
https://github.com/apache/incubator-openwhisk/blob/master/ansible/group_vars/all#L154-L159
as the higher the container count per vm the fewer vms you need

you might also want to look at work from @tysonnorris to increase intra-container concurrency so you can run more functions inside a single container at the same time which could also reduce the invoker count.

As @perryibm noted in #2569 the other parameters to take into account is the expected execution time of the actions.

**Comment by spattewar** [comment] 2017-11-14 19:06
@rabbah 
very nice information. thank you!!
quick few questions
1) I could see the limits configuration in the group vars file with default values. But what are the max limits or are the default the max limit?
2) I believe concurrentInvocationsSystem is for entire openwhisk installation including all namespaces? What is the max limit for this one/.
3) by any chance do you have an updated architecture diagram for a distributed environment.

number of container per invoker is a new concept and would read about that and would also read about the work done by @tysonnorris 

Thank you and Regards

**Comment by spattewar** [comment] 2017-11-15 14:51
@rabbah @markusthoemmes 
can you help with above. your help and time is greatly appreciated.
Regards

**Comment by rabbah** [comment] 2017-11-18 01:59
You can either use the values in the master file or change them per deployment. It's your choice since you're doing a local deployment choose what's easier for you. The `concurrentInvocationsSystem` is for the entire system at which point any new request will get rejected - the default is set to 5K but again it should be something sensible for the deployment, based on the container/invoker capacity.

@markusthoemmes's diagram is from this blog https://medium.com/openwhisk/uncovering-the-magic-how-serverless-platforms-really-work-3cb127b05f71 has a rough picture of the architecture which is accurate modulo `consul` which is no longer part of the deployment.

**Closed** 2019-12-18 15:43 UTC
Labels: deployment

**Comment by Sheshadri-1992** [comment] 2021-03-27 13:02
> OpenWhisk is being deployed distributed by default. Distributed means, that the components are distributed to multiple machines (it does not mean sharding/federation).
> 
> Locally, we deploy everything to one machine, but that is a deploytime detail. For our deployment we use [ansible](https://www.ansible.com/how-ansible-works). A deployment is defined by a group_vars file and a hosts file. One example for such a definition is the **local** environment, found here: https://github.com/apache/incubator-openwhisk/tree/master/ansible/environments/local
> 
> If you look through one of the hosts files, you'll see that there is a list of machines defined for every component individually. Fill in multiple IPs for the invokers and you'll get multiple invokers, one on each of the machines you entered (`ansible_host` is the address of the machine). In the local case that's `172.17.0.1` (docker's interface) but can really be any remote IP as well. Remoteness is "hidden" by ansible.
> 
> Let me know if you need further details!

Hello,
I am a PhD student from IISc Bangalore, I am trying a multiple invoker deployment to host a few serverless applications for my research. Using Apache OpenWhisk, I wanted to see first hand how the internals of a serverless platform work and what overheads are involved in hosting an application.
I could successfully follow steps for single server based deployment. 

However, there are some issues for distributed OpenWhisk deployment. I am listing them here.
1. Unable to issue action requests through ngnix server (Though nginx is up and running)
2. For the distributed deployment, I did edit the hosts and hosts.j2.ini file in the /openwhisk/ansible/environments/local/ (Ref : https://github.com/apache/openwhisk/blob/master/ansible/environments/local/hosts.j2.ini) to include IPs of multiple invokers
3. The invokers are not getting spawned for the remote machine. After 12 tries it is failing.

I request you to kindly suggest me on how to specify configuration files for multiple invokers.

This is my hosts file and hosts.j2.ini file, I have modified them both.
![ow-1](https://user-images.githubusercontent.com/8033368/112721346-548eae00-8f29-11eb-93e3-1f995bbfddcd.png)

This is what is happening when I run **ansible-playbook -i environments/$ENVIRONMENT openwhisk.yml**
![ow-2](https://user-images.githubusercontent.com/8033368/112721415-93bcff00-8f29-11eb-9cf7-d38a573c7bcc.png)

Two invokers are being created in the same host itself.
![ow-3](https://user-images.githubusercontent.com/8033368/112721428-ac2d1980-8f29-11eb-9fe4-b4866856c494.png)

If I set the apihost host to the ngnix ip and port, it refuses connection and returns HTTP 400 response
![ow-4](https://user-images.githubusercontent.com/8033368/112721456-d7b00400-8f29-11eb-9249-3887c0afbecf.png)

However, as suggested in one of the comments, if I set it to controller's IP and port, I can create actions and invoke them
![ow-5](https://user-images.githubusercontent.com/8033368/112721471-f1514b80-8f29-11eb-9737-874a6c8796b4.png)

These are all the services that are up and running 
![ow-6](https://user-images.githubusercontent.com/8033368/112721497-11810a80-8f2a-11eb-94c9-b81f649cbcc2.png)

I followed the deployment instructions given in this url : https://github.com/apache/openwhisk/blob/master/ansible/README.md

Awaiting your valuable suggestions! @rabbah @spattewar @markusthoemmes

**Comment by Sheshadri-1992** [comment] 2021-03-29 18:19
I shall try the solution given in this link, will update after it.
url : https://github.com/apache/openwhisk/blob/master/ansible/environments/jenkins/openwhisk-vm1-he-de.j2.ini

**Comment by rabbah** [comment] 2021-03-29 19:38
If you're not deploying to k8s, then using the ansible files you've referenced as a model is a good starting point.
